# Instantiating arrays
Julia offers native support for multi-dimensional arrays and "array programming" similar to MATLAB.
There are different ways to instantiate arrays; for example, you can initialize an empty $4 \times 4$ array that will
contain only double precision floats (`Float64`) as

In [1]:
A = Array{Float64, 2}(undef, 4, 4)

4×4 Matrix{Float64}:
 2.14315e-314  2.14315e-314  0.0  0.0
 5.3e-322      8.84e-322     0.0  0.0
 2.14315e-314  0.0           0.0  0.0
 8.35e-322     0.0           0.0  0.0

In this particular case, `Matrix{T}` is an alias type of `Array{Float64, 2}`, so you can also initialize it as

In [2]:
A = Matrix{Float64}(undef, 4, 4)

4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

Other common `Array` constructors are `zeros`, `ones`, `fill`, and `rand`

In [3]:
A = zeros(4, 4)

4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [4]:
A = ones(4, 4)

4×4 Matrix{Float64}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [5]:
A = fill(4, 4)

4-element Vector{Int64}:
 4
 4
 4
 4

In [6]:
A = rand(4, 4)

4×4 Matrix{Float64}:
 0.95417   0.456829  0.718908  0.428308
 0.989655  0.17084   0.864178  0.625751
 0.580083  0.492063  0.311881  0.509103
 0.831883  0.563287  0.68434   0.727435

# Array indexing and mutation
To read individual elements of an array, we use square brackets

In [7]:
A = rand(4)
A[1]

0.7674683187149418

In [8]:
B = rand(4, 4)
B[1, 1]

0.9126838869572659

In [9]:
C = rand(4, 4, 4)
C[1, 1, 1]

0.21634533832756941

We can also read chunks of the array at once (_NOTE_ this will allocate a new array)

In [10]:
B[1:2, 1:2]

2×2 Matrix{Float64}:
 0.912684  0.838086
 0.649304  0.22111

To make a view of an array and avoid allocating new intermediate arrays, we can use the macro `@views`

In [11]:
@views B[1:2, 1:2]

2×2 view(::Matrix{Float64}, 1:2, 1:2) with eltype Float64:
 0.912684  0.838086
 0.649304  0.22111

As in MATLAB, we can also slice `Array`s

In [12]:
@views B[:, 1] # take the first column

4-element view(::Matrix{Float64}, :, 1) with eltype Float64:
 0.9126838869572659
 0.6493040512304186
 0.8429213886710439
 0.7184174531757884

In [13]:
@views B[1, :] # take the first row

4-element view(::Matrix{Float64}, 1, :) with eltype Float64:
 0.9126838869572659
 0.838086007674934
 0.7081457691848612
 0.32596268463484646

# Broadcasting
`Array`s support element-wise (broadcasting) linear algebra operators, we only need to add a dot `.` before the operator. For example

In [14]:
A = rand(4, 4)
B = rand(4, 4)
C = A .+ B

4×4 Matrix{Float64}:
 0.905178  1.01826  0.108175  0.406362
 0.998729  1.59776  0.260611  1.69662
 1.29002   1.4254   1.03904   1.40882
 0.625926  1.24421  0.142354  0.405477

In [15]:
D = A ./ B

4×4 Matrix{Float64}:
 0.991087  0.181298  3.91544    0.845069
 4.00612   0.971274  0.456839   1.06402
 1.34225   2.27386   1.11596    0.468768
 5.66158   1.44461   0.0686793  0.0680844

If we need to broadcast several operators in a single line, we can fuse them with the `@.` macro

In [16]:
E = @. (A + B) * B^2

4×4 Matrix{Float64}:
 0.187077    0.756574  5.23903e-5  0.0197113
 0.0397503   1.04964   0.00833983  1.14638
 0.391316    0.270206  0.250539    1.29616
 0.00552605  0.322302  0.00252587  0.0584371

Broadcasting does not apply only to operators, but to any function that acts on scalars. For example, we can broadcast `sin` to any `Array`

In [17]:
sin.(A)

4×4 Matrix{Float64}:
 0.435472  0.15564   0.0860609   0.185047
 0.716817  0.708408  0.0816322   0.767301
 0.673742  0.836034  0.520972    0.434637
 0.507228  0.670772  0.00914832  0.025844

# Functions
Functions can be instantiated in several ways, with the "standard" way being

In [18]:
function foo(x)
    y = x + rand()
    return y
end

foo (generic function with 1 method)

A function (or code block, i.e. `if/elseif` statements or `let` blocks) will return their **last line**. Therefore, we can also write the previous function as

In [19]:
function foo(x)
    y = x + rand()
    y
end

foo (generic function with 1 method)

In [20]:
function foo(x)
    y = x + rand()
end

foo (generic function with 1 method)

or more concisely as a one-liner

In [21]:
foo(x) = x + rand()

foo (generic function with 1 method)

Functions can also return multiple arguments

In [22]:
function foo(x)
    y = x + rand()
    return x, y
end

foo (generic function with 1 method)

Anonymous functions also exist in Julia

In [23]:
fun = x -> x + rand()
fun(5)

5.701358170214397

All the information regarding functions can be found [here](https://docs.julialang.org/en/v1/manual/functions/)

## In-place vs out-of-place functions
It is common that you need to store the results of matrix operations in a new array. Creating the new destination array will obviously allocate, if you need to do this operation just once, an out-of-place kernel will do just fine

In [24]:
function outofplace(A, B)
    C = similar(A)
    for i in axes(A, 1), j in axes(A, 2)
        C[i, j] = B[i, j] * C[i, j]
    end
    return C
end

outofplace (generic function with 1 method)

however, it is frequent you need to run the kernel several times, in which case you want to avoid allocating the destination array every time. In this case, you can use an in-place kernel, by pre-allocating the destination array and just mutating it:

In [25]:
function inplace!(C, A, B)
    for i in axes(A, 1), j in axes(A, 2)
        C[i, j] = B[i, j] * C[i, j]
    end
    return nothing
end

inplace! (generic function with 1 method)

note that in the latter case we do not return anything, as Julia passes arguments by reference to the functions.
Also note the `!` at the end for the in-place function, this is a convention in Julia to denote that the function mutates its arguments (where the mutating arguments are the first ones).

# Benchmarking
In Julia, it is extremely easy (and extremely useful to catch performance issues or regressions) to benchmark the performance of any function.
Julia has the built-in `@time` and `@elapsed` macros that measure the performance of a single function call. However, these are not
very accurate and it's best to use external packages, namely [BenchmarkTools.jl](https://juliaci.github.io/BenchmarkTools.jl/stable/) or [Chairmarks](https://github.com/LilithHafner/Chairmarks.jl)
We can benchmark our `outofplace` and `inplace!` functions with `BenchmarkTools.jl`

In [26]:
using BenchmarkTools
A, B, C = rand(32, 32), rand(32, 32), zeros(32, 32)
@benchmark outofplace($A, $B)

BenchmarkTools.Trial: 10000 samples with 163 evaluations.
 Range (min … max):  646.221 ns … 238.168 μs  ┊ GC (min … max):  0.00% … 99.52%
 Time  (median):       1.149 μs               ┊ GC (median):     0.00%
 Time  (mean ± σ):     1.560 μs ±   3.346 μs  ┊ GC (mean ± σ):  26.41% ± 15.99%

  ▅▆█▆▃▁                                                        ▂
  ██████▇▅▅▄▅▁▄▃▁▁▃▁▁▁▁▁▁▃▁▁▁▁▁▁▁▁▁▁▃▁▁▁▁▁▁▁▃▁▄▄▅▅▅▆▅▇▅▇▆▇▇▇▇▇▇ █
  646 ns        Histogram: log(frequency) by time       13.3 μs <

 Memory estimate: 8.08 KiB, allocs estimate: 3.

In [27]:
@benchmark inplace!($C, $A, $B)

BenchmarkTools.Trial: 10000 samples with 190 evaluations.
 Range (min … max):  530.700 ns …  4.957 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     549.563 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   565.547 ns ± 92.890 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

  █ ▁▄▅▂▆▄▂▃▂▁▁▁                                               ▁
  ██████████████████▇▇▇▆▇▆▆▆▆▆▆▅▆▆▅▆▅▆▆▄▃▄▅▅▃▃▄▅▃▃▅▃▃▃▃▄▃▄▂▃▄▄ █
  531 ns        Histogram: log(frequency) by time       892 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.

or with `Chairmarks.jl`

In [28]:
using Chairmarks
@be outofplace($A, $B)

Benchmark: 1851 samples with 25 evaluations
min    660.000 ns (3 allocs: 8.078 KiB)
median 1.450 μs (3 allocs: 8.078 KiB)
mean   1.932 μs (3 allocs: 8.078 KiB, 0.05% gc time)
max    772.100 μs (3 allocs: 8.078 KiB, 99.73% gc time)

In [29]:
@be inplace!($C, $A, $B)

Benchmark: 3079 samples with 55 evaluations
min    529.545 ns
median 532.582 ns
mean   545.744 ns
max    2.394 μs

# Code parallelization
Julia supports parallel computing on both CPUs and GPUs throught different packages
- CPU:
  1. [Threads.jl](https://docs.julialang.org/en/v1/manual/multi-threading/) for multithreading (i.e. shared memory)
  2. [Distributed.jl](https://docs.julialang.org/en/v1/stdlib/Distributed/) for distributed parallelization (i.e. across multiple CPUs)
  3. [MPI.jl](https://github.com/JuliaParallel/MPI.jl) for distributed parallelization (i.e. across multiple CPUs)
- GPU:
  1. [CUDA.jl](https://github.com/JuliaGPU/CUDA.jl) for Nvidia GPU cards
  2. [AMDGPU.jl](https://github.com/JuliaGPU/AMDGPU.jl) for AMD GPU cards
  3. [Metal.jl](https://github.com/JuliaGPU/Metal.jl) for Apple M-series chips

## Multithreading
Julia does not parallelize code automatically, but it provides tools to do so. This means that "array-style programming" ala MATLAB or Numpy will not automatically parallelize in Julia.
However, is is very simple to paralleliza loops (and **loops are fast**) in Julia.
For example, let's parallelize the AXPY ("A·X Plus Y") BLAS kernel

$$A = \alpha B + C$$

where $B$ and $C$ are random $n\times n$ matrices.

In [30]:
n    = 128
α    = rand()
Z    = zeros(n, n)
X, Y = rand(n, n), rand(n, n)

([0.9017577335196968 0.26362597419050116 … 0.815485015563698 0.5390991405661553; 0.7552910855718593 0.20251391761106563 … 0.16989708483661548 0.2862445581497084; … ; 0.7164209975478115 0.8030591530654273 … 0.3253417860612724 0.13110843391669236; 0.10510440338622262 0.16728178127283078 … 0.8832041533430278 0.9654639603035552], [0.5623499335550435 0.6807843549477879 … 0.9431753772464664 0.9822629803628565; 0.989402682608007 0.30493412139134213 … 0.33470820547071434 0.050917087524446236; … ; 0.3118613399272522 0.6863504100768406 … 0.7478398918188336 0.24349331212780168; 0.30216638248886607 0.4869803198603445 … 0.20406090108241748 0.31505428764359833])

To parallelize this operation, we simply need to write the kernel as a loop and the put the `Threads.@threads` macro before the loop

In [31]:
function axpy!(Z, X, Y, α)
    @assert size(Z) == size(X) == size(Y)
    Threads.@threads for i in eachindex(X)
        Z[i] = α * X[i] + Y[i]
    end
end

axpy! (generic function with 1 method)

## GPU programming
Unlike with CPU code, broadcasting works and one can run GPU-accelerated  "array-style programming" code, as long as the arrays are properly allocated on the GPU device. For example, the AXPY operation can be run on the GPU of a M-series chip as follows:

In [32]:
using Metal
n    = 128
α    = rand(Float32)
Z    = Metal.zeros(n, n)
X, Y = Metal.rand(n, n), Metal.rand(n, n)
Z    = @. α * X + Y

128×128 Metal.MtlMatrix{Float32, Metal.PrivateStorage}:
 0.815596   0.46488   0.172365  0.567152   …  0.394312  0.954644  0.0638175
 0.0647891  0.425158  0.778653  0.339724      1.15946   0.734933  0.789722
 0.610507   0.817783  0.786538  0.828534      0.678247  0.960341  0.417979
 0.733641   0.500035  0.540654  0.309561      1.10047   0.610939  0.554279
 0.975635   0.950932  0.90331   1.06185       0.97306   0.915283  0.912188
 0.60448    0.943942  0.295774  0.489803   …  0.337867  0.942225  0.867952
 0.555816   0.537579  0.733592  0.904657      0.244592  0.812801  0.88357
 0.43215    0.730572  0.788118  0.538585      0.593145  0.898982  0.455808
 0.373605   0.966982  0.979465  0.741311      0.714037  0.798405  0.753471
 0.294809   0.636492  1.23228   0.387727      0.340071  1.02004   0.21748
 ⋮                                         ⋱  ⋮                   
 0.783568   0.285133  0.709449  0.179245      0.128245  0.24625   0.314937
 0.298081   0.598472  0.505408  0.903033   …  0.80864

If you have a NVIDIA or AMD GPU card, you can respectively use the CUDA.jl or AMDGPU.jl packages to run the same code just using the `CUDA.zeros`, `CUDA.rand` or `AMDGPU.zeros`, `AMDGPU.rand` allocators instead.
However, it is often more convinient to write function kernels, as not everything can be efficiently written an array programming style.

<p align="center">
<img src="../figs/cuda_grid.png" alt="drawing" width="300"/>
</p>

Using first linear indexing, the previous example would be written as follows

In [33]:
function axpy!(Z, X, Y, α)
    i = thread_position_in_grid_1d()
    if i ≤ length(Z)
        Z[i] = α * X[i] + Y[i]
    end
    return
end

nthreads = 512
ngroups  = cld(n^2, nthreads)
@metal threads = nthreads groups=ngroups axpy!(Z, X, Y, α)

Metal.HostKernel{typeof(Main.var"##286".axpy!), Tuple{Metal.MtlDeviceMatrix{Float32, 1}, Metal.MtlDeviceMatrix{Float32, 1}, Metal.MtlDeviceMatrix{Float32, 1}, Float32}}(Main.var"##286".axpy!, Metal.MTL.MTLComputePipelineStateInstance (object of type AGXG14XFamilyComputePipeline))

Or like this if we prefer to use Cartesian indexing:

In [34]:
function axpy_Metal!(Z, X, Y, α)
    (i,j) = thread_position_in_grid_2d()
    if i ≤ size(Z, 1) && j ≤ size(Z, 2)
        Z[i, j] = α * X[i, j] + Y[i, j]
    end
    return
end

nthreads = 16, 16
ngroups  = cld.(n, nthreads)
Metal.@sync @metal threads = nthreads groups=ngroups axpy_Metal!(Z, X, Y, α)

Metal.HostKernel{typeof(Main.var"##286".axpy_Metal!), Tuple{Metal.MtlDeviceMatrix{Float32, 1}, Metal.MtlDeviceMatrix{Float32, 1}, Metal.MtlDeviceMatrix{Float32, 1}, Float32}}(Main.var"##286".axpy_Metal!, Metal.MTL.MTLComputePipelineStateInstance (object of type AGXG14XFamilyComputePipeline))

> [!WARNING]
> Multithreaded and GPU code **is not thread safe**. It is up to the user to avoid race conditions. An example of non thread-safe code is a reduction:

In [35]:
let
    A = rand(20)
    sum = 0.0
    Threads.@threads for Ai in A
        sum += Ai # <- race condition
    end
end

# Backend abstraction
As you can see, if we want to write a code that is highly portable and run it multiple backends, we need to write a specific kernel for each hardware.
This is tedious and leads to a lot of code redudancy and prone to copy-pasting bugs. One of the advantages of Julia, is that we can easily write code that is agnostic to the backend.
This is done using one of these packages:
  - [ParallelStencil.jl](https://github.com/omlins/ParallelStencil.jl); supports CUDA.jl, AMDGPU.jl, and Metal.jl.
  - [KernelAbstractions.jl](https://github.com/JuliaGPU/KernelAbstractions.jl); supports CUDA.jl and AMDGPU.jl.

## ParallelStencil.jl
Kernel parallelization is essentially done using two new macros: `@parallel` and `@parallel_indices`

In [36]:
using ParallelStencil
@init_parallel_stencil(Threads, Float64, 2) # @init_parallel_stencil(Backend, TypePrecission, Dimension)

n    = 128
α    = rand()
Z    = @zeros(n, n)
X, Y = @rand(n, n), @rand(n, n)

@parallel_indices (i,j) function axpy_PS!(Z, X, Y, α)
    Z[i, j] = α * X[i, j] + Y[i, j]
    return
end

@parallel (1:n, 1:n) axpy_PS!(Z, X, Y, α)

## KernelAbstractions.jl
This package requires a bit more written, as now we need to define a kernel and a launcher function to parallelize our code

In [37]:
using Metal # comment out to run on the CPU; or load CUDA / AMDGPU instead
using KernelAbstractions, Random

backend = MetalBackend() # other valid backends: CPU(), CUDABackend(), AMDGPUBackend()
type    = Float32
n       = 128
α       = rand(type)
Z       = KernelAbstractions.zeros(backend, type, n, n)
X       = rand!(allocate(backend, type, n, n))
Y       = rand!(allocate(backend, type, n, n))

128×128 Metal.MtlMatrix{Float32, Metal.PrivateStorage}:
 0.590338   0.148476   0.309626  …  0.734281   0.17075      0.46747
 0.816651   0.738104   0.408657     0.70122    0.980236     0.473899
 0.306998   0.817772   0.474625     0.44708    0.769124     0.08973
 0.610878   0.759066   0.581855     0.0176271  0.0149094    0.329428
 0.323795   0.222844   0.69302      0.651956   0.912801     0.52422
 0.535055   0.62285    0.170234  …  0.320966   0.710759     0.91978
 0.887648   0.795175   0.589949     0.235552   0.155195     0.219062
 0.698051   0.321051   0.286161     0.839727   0.650872     0.857994
 0.538854   0.0149783  0.219537     0.793466   0.155159     0.160329
 0.164456   0.643001   0.985792     0.956448   0.376456     0.290343
 ⋮                               ⋱  ⋮                       
 0.836447   0.467763   0.674723     0.988468   0.967462     0.671614
 0.0134086  0.0804033  0.560772  …  0.919006   0.92813      0.133023
 0.0738519  0.693142   0.153843     0.242448   0.0284514   

kernel

In [38]:
@kernel function axpy_KA_kernel!(Z, X, Y, α)
    i, j = @index(Global, NTuple)
    Z[i, j] = α * X[i, j] + Y[i, j]
end

axpy_KA_kernel! (generic function with 4 methods)

launcher

In [39]:
function axpy_KA!(Z, X, Y, α)
    backend = get_backend(Z)
    @assert size(X) == size(Y) == size(Z)
    @assert get_backend(X) == get_backend(Y) == backend

    nthreads = 32, 32
    kernel = axpy_KA_kernel!(backend, nthreads)
    kernel(Z, X, Y, α, ndrange = size(Z))
    KernelAbstractions.synchronize(backend)
    return
end

axpy_KA! (generic function with 1 method)

---

*This notebook was generated using [Literate.jl](https://github.com/fredrikekre/Literate.jl).*